"""empty message

Revision ID: bb69d11c5d73
Revises: 51f5ccfba190
Create Date: 2017-10-01 18:59:27.704652

"""

# revision identifiers, used by Alembic.
revision = 'bb69d11c5d73'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
